instant-respawn: true

messages:
  usage: "<gradient:#FFA7D9:#FFA7D9>UniDeath</gradient> <gray>-> <red>Usage: /unideath reload"
  successful-reload: "<gradient:#FFA7D9:#FFA7D9>UniDeath</gradient> <gray>-> <green>Config reload successful!</green>"
  no-permission: "<gradient:#FFA7D9:#FFA7D9>UniDeath</gradient> <gray>-> <red>You don't have permission to do this!"