instant-respawn: true

messages:
  usage: "&#FFA7D9UniDeath &7-> &cUsage: /unideath reload"
  successful-reload: "&#FFA7D9UniDeath &7-> &aConfig reload successful!"
  no-permission: "&#FFA7D9UniDeath &7-> &cYou don't have permission to do this!"